# Generated by Django 6.0.2 on 2026-03-05 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pokemon", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PokemonType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name="pokemon",
            name="types",
            field=models.ManyToManyField(to="pokemon.pokemontype"),
        ),
    ]
